service: chatbot-flask

provider:
    name: aws
    runtime: python3.8
    stage: dev
    region: ap-northeast-2

functions:
    flaskApp:
        handler: app.handler
        events:
            - http:
                  path: /
                  method: any
            - http:
                  path: '{proxy+}'
                  method: any

plugins:
    - serverless-wsgi
    - serverless-python-requirements

custom:
    wsgi:
        app: app.app
        packRequirements: false
    pythonRequirements:
        dockerizePip: non-linux

package:
    exclude:
        - .envrc
        - README.md
        - package.json
