import { Metadata } from 'next';
import { PropsWithChildren } from 'react';

import './globals.css';
import { Providers } from './providers';

export const metadata: Metadata = {
    description: 'Generated by create next app',
    title: 'Create Next App',
};

export default function RootLayout({ children }: PropsWithChildren) {
    return (
        <html lang="en">
            <body>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
