service: vite-ssr
frameworkVersion: '3'

plugins:
    - serverless-esbuild
    - serverless-offline

custom:
    esbuild:
        config: esbuild-config.cjs

provider:
    name: aws
    region: ap-northeast-2
    profile: serverless-admin
    deploymentMethod: direct
    runtime: nodejs18.x
    memorySize: 1536 # mb
    timeout: 15 # seconds
    versionFunctions: false
    httpApi:
        cors: true

package:
    individually: true

functions:
    vsp:
        handler: server/lambda.handler
        layers:
            - arn:aws:lambda:ap-northeast-2:617550243627:layer:aws-sdk-layer:1
        environment:
            NODE_ENV: production
        package:
            individually: true
        events:
            - httpApi: '*'
